# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Get today's crossword

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1,2,3,4,5,6" # Mon-Sat @ 6am UTC

env:
  SUPERNOTE_CLOUD_EMAIL: ${{ secrets.SUPERNOTE_CLOUD_EMAIL }}
  SUPERNOTE_CLOUD_PASSWORD: ${{ secrets.SUPERNOTE_CLOUD_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm install
    - run: node index.js
